/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AutonomousStateMachine.sm
 */

package org.firstinspires.ftc.teamcode.autonomous;


public class AutonomousStateMachineContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public AutonomousStateMachineContext(AutonomousController owner)
    {
        this (owner, AutonomousStateMachine.Idle);
    }

    public AutonomousStateMachineContext(AutonomousController owner, AutonomousControllerState initState)
    {
        super (initState);

        _owner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
        return;
    }

    public void evFourRings()
    {
        _transition = "evFourRings";
        getState().evFourRings(this);
        _transition = "";
        return;
    }

    public void evMoveComplete()
    {
        _transition = "evMoveComplete";
        getState().evMoveComplete(this);
        _transition = "";
        return;
    }

    public void evNoRings()
    {
        _transition = "evNoRings";
        getState().evNoRings(this);
        _transition = "";
        return;
    }

    public void evOneRing()
    {
        _transition = "evOneRing";
        getState().evOneRing(this);
        _transition = "";
        return;
    }

    public void evRotationComplete()
    {
        _transition = "evRotationComplete";
        getState().evRotationComplete(this);
        _transition = "";
        return;
    }

    public void evStart()
    {
        _transition = "evStart";
        getState().evStart(this);
        _transition = "";
        return;
    }

    public void evStrafeComplete()
    {
        _transition = "evStrafeComplete";
        getState().evStrafeComplete(this);
        _transition = "";
        return;
    }

    public void evTimeout()
    {
        _transition = "evTimeout";
        getState().evTimeout(this);
        _transition = "";
        return;
    }

    public void evTimeoutComplete()
    {
        _transition = "evTimeoutComplete";
        getState().evTimeoutComplete(this);
        _transition = "";
        return;
    }

    public AutonomousControllerState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((AutonomousControllerState) _state);
    }

    protected AutonomousController getOwner()
    {
        return (_owner);
    }

    public void setOwner(AutonomousController owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private AutonomousController _owner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class AutonomousControllerState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AutonomousControllerState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(AutonomousStateMachineContext context) {}
        protected void exit(AutonomousStateMachineContext context) {}

        protected void evFourRings(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evNoRings(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evOneRing(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evStart(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evStrafeComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evTimeout(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void Default(AutonomousStateMachineContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
    // Constants.
    //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class AutonomousStateMachine
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final AutonomousStateMachine_Idle Idle =
            new AutonomousStateMachine_Idle("AutonomousStateMachine.Idle", 0);
        public static final AutonomousStateMachine_MoveForward MoveForward =
            new AutonomousStateMachine_MoveForward("AutonomousStateMachine.MoveForward", 1);
        public static final AutonomousStateMachine_StrafeLeftToMeasure StrafeLeftToMeasure =
            new AutonomousStateMachine_StrafeLeftToMeasure("AutonomousStateMachine.StrafeLeftToMeasure", 2);
        public static final AutonomousStateMachine_MeasureRing MeasureRing =
            new AutonomousStateMachine_MeasureRing("AutonomousStateMachine.MeasureRing", 3);
        public static final AutonomousStateMachine_Stop Stop =
            new AutonomousStateMachine_Stop("AutonomousStateMachine.Stop", 4);
    }

    protected static class AutonomousStateMachine_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AutonomousStateMachine_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_Idle
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_Idle(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void evStart(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(AutonomousStateMachine.MoveForward);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_MoveForward
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_MoveForward(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(26d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(AutonomousStateMachine.StrafeLeftToMeasure);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_StrafeLeftToMeasure
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_StrafeLeftToMeasure(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.strafe(-2d);
            return;
        }

        @Override
        protected void evStrafeComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(AutonomousStateMachine.MeasureRing);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_MeasureRing
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_MeasureRing(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.activateRingDetector();
            ctxt.startTimer(3000);
            ctxt.startRingsMeasurement();
            return;
        }

        @Override
        protected void exit(AutonomousStateMachineContext context)
            {
            AutonomousController ctxt = context.getOwner();

            ctxt.deactivateRingDetector();
            return;
        }

        @Override
        protected void evFourRings(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.Start);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evNoRings(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.Start);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evOneRing(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.Start);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_Stop
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class NoRingSequence
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final NoRingSequence_Start Start =
            new NoRingSequence_Start("NoRingSequence.Start", 5);
        public static final NoRingSequence_RotateToSquareA RotateToSquareA =
            new NoRingSequence_RotateToSquareA("NoRingSequence.RotateToSquareA", 6);
        public static final NoRingSequence_DropWobbleGoal DropWobbleGoal =
            new NoRingSequence_DropWobbleGoal("NoRingSequence.DropWobbleGoal", 7);
        public static final NoRingSequence_MoveToPowerShot MoveToPowerShot =
            new NoRingSequence_MoveToPowerShot("NoRingSequence.MoveToPowerShot", 8);
        public static final NoRingSequence_ShootPowerShot ShootPowerShot =
            new NoRingSequence_ShootPowerShot("NoRingSequence.ShootPowerShot", 9);
        public static final NoRingSequence_MoveToWhiteLine MoveToWhiteLine =
            new NoRingSequence_MoveToWhiteLine("NoRingSequence.MoveToWhiteLine", 10);
        public static final NoRingSequence_Stop Stop =
            new NoRingSequence_Stop("NoRingSequence.Stop", 11);
    }

    protected static class NoRingSequence_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected NoRingSequence_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_Start
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(49d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.RotateToSquareA);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_RotateToSquareA
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_RotateToSquareA(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(-90);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.DropWobbleGoal);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(6d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_DropWobbleGoal
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_DropWobbleGoal(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.openGrabber();
            ctxt.startTimer(500);
            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.activateShooter();
            }
            finally
            {
                context.setState(NoRingSequence.MoveToPowerShot);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_MoveToPowerShot
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_MoveToPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-36d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.rotateToHeading(0);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.ShootPowerShot);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_ShootPowerShot
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_ShootPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.shootRing();
                ctxt.startTimer(2000);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.MoveToWhiteLine);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_MoveToWhiteLine
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_MoveToWhiteLine(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.Stop);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_Stop
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class OneRingSequence
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final OneRingSequence_Start Start =
            new OneRingSequence_Start("OneRingSequence.Start", 12);
        public static final OneRingSequence_GotoSquareB GotoSquareB =
            new OneRingSequence_GotoSquareB("OneRingSequence.GotoSquareB", 13);
        public static final OneRingSequence_MoveIntoSquareB MoveIntoSquareB =
            new OneRingSequence_MoveIntoSquareB("OneRingSequence.MoveIntoSquareB", 14);
        public static final OneRingSequence_DropWobbleGoal DropWobbleGoal =
            new OneRingSequence_DropWobbleGoal("OneRingSequence.DropWobbleGoal", 15);
        public static final OneRingSequence_RotateToGoal RotateToGoal =
            new OneRingSequence_RotateToGoal("OneRingSequence.RotateToGoal", 16);
        public static final OneRingSequence_StrafeToPowerShot StrafeToPowerShot =
            new OneRingSequence_StrafeToPowerShot("OneRingSequence.StrafeToPowerShot", 17);
        public static final OneRingSequence_DoPowerShot DoPowerShot =
            new OneRingSequence_DoPowerShot("OneRingSequence.DoPowerShot", 18);
        public static final OneRingSequence_MoveToWhiteLine MoveToWhiteLine =
            new OneRingSequence_MoveToWhiteLine("OneRingSequence.MoveToWhiteLine", 19);
        public static final OneRingSequence_Stop Stop =
            new OneRingSequence_Stop("OneRingSequence.Stop", 20);
    }

    protected static class OneRingSequence_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected OneRingSequence_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_Start
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.strafe(-24d);
            return;
        }

        @Override
        protected void evStrafeComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.GotoSquareB);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_GotoSquareB
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_GotoSquareB(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(73d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.rotateToHeading(90);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.MoveIntoSquareB);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_MoveIntoSquareB
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_MoveIntoSquareB(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(6d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.DropWobbleGoal);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_DropWobbleGoal
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_DropWobbleGoal(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.openGrabber();
            ctxt.startTimer(500);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.RotateToGoal);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(-6d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_RotateToGoal
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_RotateToGoal(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(0);
            ctxt.activateShooter();
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.StrafeToPowerShot);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(-36d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_StrafeToPowerShot
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_StrafeToPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.startTimer(1000);
            return;
        }

        @Override
        protected void evStrafeComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.DoPowerShot);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.strafe(24);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_DoPowerShot
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_DoPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.shootRing();
            ctxt.startTimer(2000);
            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.MoveToWhiteLine);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_MoveToWhiteLine
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_MoveToWhiteLine(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.Stop);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_Stop
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class FourRingsSequence
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final FourRingsSequence_Start Start =
            new FourRingsSequence_Start("FourRingsSequence.Start", 21);
        public static final FourRingsSequence_RotateToSquareA RotateToSquareA =
            new FourRingsSequence_RotateToSquareA("FourRingsSequence.RotateToSquareA", 22);
        public static final FourRingsSequence_RotateToPowerShot RotateToPowerShot =
            new FourRingsSequence_RotateToPowerShot("FourRingsSequence.RotateToPowerShot", 23);
        public static final FourRingsSequence_ShootPowerShot ShootPowerShot =
            new FourRingsSequence_ShootPowerShot("FourRingsSequence.ShootPowerShot", 24);
        public static final FourRingsSequence_MoveToWhiteLine MoveToWhiteLine =
            new FourRingsSequence_MoveToWhiteLine("FourRingsSequence.MoveToWhiteLine", 25);
        public static final FourRingsSequence_Stop Stop =
            new FourRingsSequence_Stop("FourRingsSequence.Stop", 26);
    }

    protected static class FourRingsSequence_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected FourRingsSequence_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_Start
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(49d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.RotateToSquareA);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_RotateToSquareA
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_RotateToSquareA(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(-90);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.openGrabber();
                ctxt.startTimer(500);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(-6d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.activateShooter();
            }
            finally
            {
                context.setState(FourRingsSequence.RotateToPowerShot);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_RotateToPowerShot
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_RotateToPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-36d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.rotateToHeading(0);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.ShootPowerShot);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_ShootPowerShot
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_ShootPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.shootRing();
                ctxt.startTimer(2000);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.MoveToWhiteLine);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_MoveToWhiteLine
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_MoveToWhiteLine(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.Stop);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_Stop
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
