/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AutonomousStateMachine.sm
 */

package org.firstinspires.ftc.teamcode.autonomous;


public class AutonomousStateMachineContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public AutonomousStateMachineContext(AutonomousController owner)
    {
        this (owner, AutonomousStateMachine.Idle);
    }

    public AutonomousStateMachineContext(AutonomousController owner, AutonomousControllerState initState)
    {
        super (initState);

        _owner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
        return;
    }

    public void evMoveComplete()
    {
        _transition = "evMoveComplete";
        getState().evMoveComplete(this);
        _transition = "";
        return;
    }

    public void evReadyToShoot()
    {
        _transition = "evReadyToShoot";
        getState().evReadyToShoot(this);
        _transition = "";
        return;
    }

    public void evRotationComplete()
    {
        _transition = "evRotationComplete";
        getState().evRotationComplete(this);
        _transition = "";
        return;
    }

    public void evStartDemo()
    {
        _transition = "evStartDemo";
        getState().evStartDemo(this);
        _transition = "";
        return;
    }

    public void evTimeout()
    {
        _transition = "evTimeout";
        getState().evTimeout(this);
        _transition = "";
        return;
    }

    public AutonomousControllerState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((AutonomousControllerState) _state);
    }

    protected AutonomousController getOwner()
    {
        return (_owner);
    }

    public void setOwner(AutonomousController owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private AutonomousController _owner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class AutonomousControllerState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AutonomousControllerState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(AutonomousStateMachineContext context) {}
        protected void exit(AutonomousStateMachineContext context) {}

        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evReadyToShoot(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evStartDemo(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evTimeout(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void Default(AutonomousStateMachineContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
    // Constants.
    //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class AutonomousStateMachine
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final AutonomousStateMachine_Idle Idle =
            new AutonomousStateMachine_Idle("AutonomousStateMachine.Idle", 0);
    }

    protected static class AutonomousStateMachine_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AutonomousStateMachine_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_Idle
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_Idle(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void evStartDemo(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(Demo.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class Demo
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final Demo_Start Start =
            new Demo_Start("Demo.Start", 1);
        public static final Demo_Rotate Rotate =
            new Demo_Rotate("Demo.Rotate", 2);
        public static final Demo_ActivateShooter ActivateShooter =
            new Demo_ActivateShooter("Demo.ActivateShooter", 3);
        public static final Demo_Shooting Shooting =
            new Demo_Shooting("Demo.Shooting", 4);
        public static final Demo_Shutdown Shutdown =
            new Demo_Shutdown("Demo.Shutdown", 5);
        public static final Demo_Complete Complete =
            new Demo_Complete("Demo.Complete", 6);
    }

    protected static class Demo_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected Demo_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Demo_Start
        extends Demo_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Demo_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-24d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(Demo.ActivateShooter);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Demo_Rotate
        extends Demo_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Demo_Rotate(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(180);
            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(Demo.ActivateShooter);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Demo_ActivateShooter
        extends Demo_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Demo_ActivateShooter(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.activateShooter();
            return;
        }

        @Override
        protected void evReadyToShoot(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(Demo.Shooting);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Demo_Shooting
        extends Demo_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Demo_Shooting(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.shootRing();
            ctxt.startTimer(3000);
            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(Demo.Shutdown);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Demo_Shutdown
        extends Demo_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Demo_Shutdown(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.deactivateShooter();
            ctxt.startTimer(1000);
            return;
        }

        @Override
        protected void evTimeout(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(Demo.Complete);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class Demo_Complete
        extends Demo_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private Demo_Complete(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
