/*
 * ex: set ro:
 * DO NOT EDIT.
 * generated by smc (http://smc.sourceforge.net/)
 * from file : AutonomousStateMachine.sm
 */

package org.firstinspires.ftc.teamcode.autonomous;


public class AutonomousStateMachineContext
    extends statemap.FSMContext
{
//---------------------------------------------------------------
// Member methods.
//

    public AutonomousStateMachineContext(AutonomousController owner)
    {
        this (owner, AutonomousStateMachine.Idle);
    }

    public AutonomousStateMachineContext(AutonomousController owner, AutonomousControllerState initState)
    {
        super (initState);

        _owner = owner;
    }

    @Override
    public void enterStartState()
    {
        getState().entry(this);
        return;
    }

    public void evFourRings()
    {
        _transition = "evFourRings";
        getState().evFourRings(this);
        _transition = "";
        return;
    }

    public void evMoveComplete()
    {
        _transition = "evMoveComplete";
        getState().evMoveComplete(this);
        _transition = "";
        return;
    }

    public void evNoRings()
    {
        _transition = "evNoRings";
        getState().evNoRings(this);
        _transition = "";
        return;
    }

    public void evOneRing()
    {
        _transition = "evOneRing";
        getState().evOneRing(this);
        _transition = "";
        return;
    }

    public void evRotationComplete()
    {
        _transition = "evRotationComplete";
        getState().evRotationComplete(this);
        _transition = "";
        return;
    }

    public void evStart()
    {
        _transition = "evStart";
        getState().evStart(this);
        _transition = "";
        return;
    }

    public void evTimeoutComplete()
    {
        _transition = "evTimeoutComplete";
        getState().evTimeoutComplete(this);
        _transition = "";
        return;
    }

    public AutonomousControllerState getState()
        throws statemap.StateUndefinedException
    {
        if (_state == null)
        {
            throw(
                new statemap.StateUndefinedException());
        }

        return ((AutonomousControllerState) _state);
    }

    protected AutonomousController getOwner()
    {
        return (_owner);
    }

    public void setOwner(AutonomousController owner)
    {
        if (owner == null)
        {
            throw (
                new NullPointerException(
                    "null owner"));
        }
        else
        {
            _owner = owner;
        }

        return;
    }

//---------------------------------------------------------------
// Member data.
//

    transient private AutonomousController _owner;

    //-----------------------------------------------------------
    // Constants.
    //

    private static final long serialVersionUID = 1L;

//---------------------------------------------------------------
// Inner classes.
//

    public static abstract class AutonomousControllerState
        extends statemap.State
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AutonomousControllerState(String name, int id)
        {
            super (name, id);
        }

        protected void entry(AutonomousStateMachineContext context) {}
        protected void exit(AutonomousStateMachineContext context) {}

        protected void evFourRings(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evNoRings(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evOneRing(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evStart(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {
            Default(context);
        }

        protected void Default(AutonomousStateMachineContext context)
        {
            throw (
                new statemap.TransitionUndefinedException(
                    "State: " +
                    context.getState().getName() +
                    ", Transition: " +
                    context.getTransition()));
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
    // Constants.
    //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class AutonomousStateMachine
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final AutonomousStateMachine_Idle Idle =
            new AutonomousStateMachine_Idle("AutonomousStateMachine.Idle", 0);
        public static final AutonomousStateMachine_Start Start =
            new AutonomousStateMachine_Start("AutonomousStateMachine.Start", 1);
        public static final AutonomousStateMachine_MeasureRing MeasureRing =
            new AutonomousStateMachine_MeasureRing("AutonomousStateMachine.MeasureRing", 2);
    }

    protected static class AutonomousStateMachine_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected AutonomousStateMachine_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_Idle
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_Idle(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void evStart(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(AutonomousStateMachine.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_Start
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(22d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(AutonomousStateMachine.MeasureRing);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class AutonomousStateMachine_MeasureRing
        extends AutonomousStateMachine_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private AutonomousStateMachine_MeasureRing(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.activateRingDetector();
            ctxt.startTimer(5000);
            ctxt.startRingsMeasurement();
            return;
        }

        @Override
        protected void exit(AutonomousStateMachineContext context)
            {
            AutonomousController ctxt = context.getOwner();

            ctxt.deactivateRingDetector();
            return;
        }

        @Override
        protected void evFourRings(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.Start);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evNoRings(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.Start);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evOneRing(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.Start);
            (context.getState()).entry(context);
            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.Start);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class NoRingSequence
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final NoRingSequence_Start Start =
            new NoRingSequence_Start("NoRingSequence.Start", 3);
        public static final NoRingSequence_RotateToSquareA RotateToSquareA =
            new NoRingSequence_RotateToSquareA("NoRingSequence.RotateToSquareA", 4);
        public static final NoRingSequence_RotateToPowerShot RotateToPowerShot =
            new NoRingSequence_RotateToPowerShot("NoRingSequence.RotateToPowerShot", 5);
        public static final NoRingSequence_ShootPowerShot ShootPowerShot =
            new NoRingSequence_ShootPowerShot("NoRingSequence.ShootPowerShot", 6);
        public static final NoRingSequence_MoveToWhiteLine MoveToWhiteLine =
            new NoRingSequence_MoveToWhiteLine("NoRingSequence.MoveToWhiteLine", 7);
        public static final NoRingSequence_Stop Stop =
            new NoRingSequence_Stop("NoRingSequence.Stop", 8);
    }

    protected static class NoRingSequence_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected NoRingSequence_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_Start
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(49d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.RotateToSquareA);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_RotateToSquareA
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_RotateToSquareA(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(-90);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.openGrabber();
                ctxt.startTimer(500);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(-6d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.activateShooter();
            }
            finally
            {
                context.setState(NoRingSequence.RotateToPowerShot);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_RotateToPowerShot
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_RotateToPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-36d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.rotateToHeading(0);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.ShootPowerShot);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_ShootPowerShot
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_ShootPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.shootRing();
                ctxt.startTimer(2000);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.MoveToWhiteLine);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_MoveToWhiteLine
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_MoveToWhiteLine(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(NoRingSequence.Stop);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class NoRingSequence_Stop
        extends NoRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private NoRingSequence_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class OneRingSequence
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final OneRingSequence_Start Start =
            new OneRingSequence_Start("OneRingSequence.Start", 9);
        public static final OneRingSequence_RotateToSquareA RotateToSquareA =
            new OneRingSequence_RotateToSquareA("OneRingSequence.RotateToSquareA", 10);
        public static final OneRingSequence_RotateToPowerShot RotateToPowerShot =
            new OneRingSequence_RotateToPowerShot("OneRingSequence.RotateToPowerShot", 11);
        public static final OneRingSequence_ShootPowerShot ShootPowerShot =
            new OneRingSequence_ShootPowerShot("OneRingSequence.ShootPowerShot", 12);
        public static final OneRingSequence_MoveToWhiteLine MoveToWhiteLine =
            new OneRingSequence_MoveToWhiteLine("OneRingSequence.MoveToWhiteLine", 13);
        public static final OneRingSequence_Stop Stop =
            new OneRingSequence_Stop("OneRingSequence.Stop", 14);
    }

    protected static class OneRingSequence_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected OneRingSequence_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_Start
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(49d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.RotateToSquareA);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_RotateToSquareA
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_RotateToSquareA(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(-90);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.openGrabber();
                ctxt.startTimer(500);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(-6d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.activateShooter();
            }
            finally
            {
                context.setState(OneRingSequence.RotateToPowerShot);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_RotateToPowerShot
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_RotateToPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-36d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.rotateToHeading(0);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.ShootPowerShot);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_ShootPowerShot
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_ShootPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.shootRing();
                ctxt.startTimer(2000);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.MoveToWhiteLine);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_MoveToWhiteLine
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_MoveToWhiteLine(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(OneRingSequence.Stop);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class OneRingSequence_Stop
        extends OneRingSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private OneRingSequence_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    /* package */ static abstract class FourRingsSequence
    {
    //-----------------------------------------------------------
    // Member methods.
    //

    //-----------------------------------------------------------
    // Member data.
    //

        //-------------------------------------------------------
        // Constants.
        //

        public static final FourRingsSequence_Start Start =
            new FourRingsSequence_Start("FourRingsSequence.Start", 15);
        public static final FourRingsSequence_RotateToSquareA RotateToSquareA =
            new FourRingsSequence_RotateToSquareA("FourRingsSequence.RotateToSquareA", 16);
        public static final FourRingsSequence_RotateToPowerShot RotateToPowerShot =
            new FourRingsSequence_RotateToPowerShot("FourRingsSequence.RotateToPowerShot", 17);
        public static final FourRingsSequence_ShootPowerShot ShootPowerShot =
            new FourRingsSequence_ShootPowerShot("FourRingsSequence.ShootPowerShot", 18);
        public static final FourRingsSequence_MoveToWhiteLine MoveToWhiteLine =
            new FourRingsSequence_MoveToWhiteLine("FourRingsSequence.MoveToWhiteLine", 19);
        public static final FourRingsSequence_Stop Stop =
            new FourRingsSequence_Stop("FourRingsSequence.Stop", 20);
    }

    protected static class FourRingsSequence_Default
        extends AutonomousControllerState
    {
    //-----------------------------------------------------------
    // Member methods.
    //

        protected FourRingsSequence_Default(String name, int id)
        {
            super (name, id);
        }

    //-----------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_Start
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_Start(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(49d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.RotateToSquareA);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_RotateToSquareA
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_RotateToSquareA(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.rotateToHeading(270);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.openGrabber();
                ctxt.startTimer(500);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.moveStraight(-6d);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            (context.getState()).exit(context);
            context.clearState();
            try
            {
                ctxt.activateShooter();
            }
            finally
            {
                context.setState(FourRingsSequence.RotateToPowerShot);
                (context.getState()).entry(context);
            }

            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_RotateToPowerShot
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_RotateToPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-36d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.rotateToHeading(0);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evRotationComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.ShootPowerShot);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_ShootPowerShot
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_ShootPowerShot(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(-12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {
            AutonomousController ctxt = context.getOwner();

            AutonomousControllerState endState = context.getState();
            context.clearState();
            try
            {
                ctxt.shootRing();
                ctxt.startTimer(2000);
            }
            finally
            {
                context.setState(endState);
            }

            return;
        }

        @Override
        protected void evTimeoutComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.MoveToWhiteLine);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_MoveToWhiteLine
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_MoveToWhiteLine(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.moveStraight(12d);
            return;
        }

        @Override
        protected void evMoveComplete(AutonomousStateMachineContext context)
        {

            (context.getState()).exit(context);
            context.setState(FourRingsSequence.Stop);
            (context.getState()).entry(context);
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }

    private static final class FourRingsSequence_Stop
        extends FourRingsSequence_Default
    {
    //-------------------------------------------------------
    // Member methods.
    //

        private FourRingsSequence_Stop(String name, int id)
        {
            super (name, id);
        }

        @Override
        protected void entry(AutonomousStateMachineContext context)
            {
                AutonomousController ctxt = context.getOwner();

            ctxt.stop();
            return;
        }

    //-------------------------------------------------------
    // Member data.
    //

        //---------------------------------------------------
        // Constants.
        //

        private static final long serialVersionUID = 1L;
    }
}

/*
 * Local variables:
 *  buffer-read-only: t
 * End:
 */
